- name: Wait for javascript applications to be ready
  command: "oc get ep {{item}}"
  register: result
  until: result.stdout.find("none") == -1
  retries: 50
  delay: 15
  with_items:
    - mobile-app
    - mobile-app-admin
    - leaderboard
    - scoreboard