---
- name: Create temporary file for template
  tempfile:
    state: file
    suffix: json
  register: template_path

- debug:
    msg: "{{ template_path }}"

- name: Create game server template
  template:
    src: "../files/game-server-template.json"
    dest: "{{template_path.path}}"

- name: Create blue game server
  command: "oc new-app -f {{template_path.path}} -p SOURCE_REPOSITORY_URL={{ game_server_repo }} -p COLOR=blue -p APPLICATION_NAME=gamebus-blue"

- name: Create green game server
  command: "oc new-app -f {{template_path.path}} -p SOURCE_REPOSITORY_URL={{ game_server_repo }} -p COLOR=green -p APPLICATION_NAME=gamebus-green"

- name: Wait for blue game server to be ready
  command: "oc get ep gamebus-blue"
  register: result
  until: result.stdout.find("none") == -1 
  retries: 50
  delay: 10

- name: Wait for green game server to be ready
  command: "oc get ep gamebus-green"
  register: result
  until: result.stdout.find("none") == -1 
  retries: 50
  delay: 10

- name: Create gamebus blue-green routes
  shell: "oc process -p APPLICATION_NAME=gamebus -f roles/setup-game-server/files/game-server-routes.json | oc create -f -"