---
- name: Create mobile game application
  command: "oc new-app -f roles/setup-game-app/files/game-app-template.json -p APPLICATION_NAME=game-app"

- name: Wait for game application to be ready
  command: "oc get ep game-app"
  register: result
  until: result.stdout.find("none") == -1
  retries: 50
  delay: 10    