---
- name: Setup up mobile admin application
  command: "oc new-app openshift/nodejs:6~{{ mobile_admin_app_repo }}"

- name: Expose route for mobile admin application
  command: "oc expose svc mobile-app-admin"

- name: Create probes
  command: "oc set probe dc/mobile-app-admin --readiness --liveness --open-tcp=8080 --initial-delay-seconds=10"